CREATE TABLE `loan_scenarios` (
	`id` int AUTO_INCREMENT NOT NULL,
	`propertyId` int NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`propertyValue` int NOT NULL,
	`deposit` int NOT NULL,
	`loanAmount` int NOT NULL,
	`interestRate` int NOT NULL,
	`loanTerm` int NOT NULL,
	`repaymentFrequency` varchar(50) NOT NULL,
	`interestOption` varchar(50) NOT NULL,
	`offsetBalance` int DEFAULT 0,
	`extraRepaymentAmount` int DEFAULT 0,
	`extraRepaymentFrequency` varchar(50),
	`propertyGrowthRate` int NOT NULL,
	`totalInterest` int,
	`totalPayments` int,
	`futurePropertyValue` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `loan_scenarios_id` PRIMARY KEY(`id`)
);
